name: Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - shell: bash
        run: |
          pnpm install --no-frozen-lockfile
      - name: Check types and style
        run: pnpm run check
      - name: Test
        run: pnpm test
      - name: Ensure Quartz builds, check bundle info
        run: pnpx quartz build --bundleInfo
